function getPartiesData() {
  return {
  "Parties": [
    {
      "Party": "Arden",
      "StaffMemberName": "Sherri Rinell",
      "CompanionName": "Ari",
      "BackgroundColor": "#b6d7a8",
      "TableColor": "#b6d7a8",
      "TextColor": "#000000"
    },
    {
      "Party": "Claria",
      "StaffMemberName": "James Surano",
      "CompanionName": "Clem",
      "BackgroundColor": "#ffffff",
      "TableColor": "#ffffff",
      "TextColor": "#000000"
    },
    {
      "Party": "Dolorón",
      "StaffMemberName": "Maisie Sturtevant",
      "CompanionName": "Dodi",
      "BackgroundColor": "#ff9b9b",
      "TableColor": "#ff9b9b",
      "TextColor": "#000000"
    },
    {
      "Party": "Elsewhich",
      "StaffMemberName": "Lori Nadig",
      "CompanionName": "Elvie",
      "BackgroundColor": "#cccccc",
      "TableColor": "#cccccc",
      "TextColor": "#000000"
    },
    {
      "Party": "Glendeep",
      "StaffMemberName": "Steve Spodaryk",
      "CompanionName": "Gloucester",
      "BackgroundColor": "#b7e1cd",
      "TableColor": "#b7e1cd",
      "TextColor": "#000000"
    },
    {
      "Party": "Keer",
      "StaffMemberName": "Bill Sabram",
      "CompanionName": "Keifer",
      "BackgroundColor": "#c9daf8",
      "TableColor": "#c9daf8",
      "TextColor": "#000000"
    },
    {
      "Party": "Noctara",
      "StaffMemberName": "Chelsea Hadlock",
      "CompanionName": "Nadia",
      "BackgroundColor": "#b4a7d6",
      "TableColor": "#b4a7d6",
      "TextColor": "#000000"
    },
    {
      "Party": "P'loa",
      "StaffMemberName": "Bob Marriott",
      "CompanionName": "Polo",
      "BackgroundColor": "#d0e0e3",
      "TableColor": "#d0e0e3",
      "TextColor": "#000000"
    },
    {
      "Party": "Sythwan",
      "StaffMemberName": "Joyce Farnsworth",
      "CompanionName": "Silla",
      "BackgroundColor": "#fff2cc",
      "TableColor": "#fff2cc",
      "TextColor": "#000000"
    },
    {
      "Party": "Uri-Kesh",
      "StaffMemberName": "Brian Neff",
      "CompanionName": "Urving",
      "BackgroundColor": "#f4cccc",
      "TableColor": "#f4cccc",
      "TextColor": "#000000"
    },
    {
      "Party": "Waylon",
      "StaffMemberName": "Britt Rothauser",
      "CompanionName": "Waverly",
      "BackgroundColor": "#fce5cd",
      "TableColor": "#fce5cd",
      "TextColor": "#000000"
    }
  ]
  };
}

function getStaffData() {
  return [
    "Brian Scassellati",
    "Cliff Young",
    "Dorian Hart",
    "Jeff Foley",
    "Jen Platt",
    "Kristi Hayes",
    "Chris Reichert",
    "Jim Vincent",
    "Jodi Riley",
    "Merri Rosen",
    "Cris Shuldiner",
    "Kevin Kulp",
    "Peggy O'Connell",
    "Abigail Vargus",
    "Dave Korka",
    "Deb Lack",
    "Paul San Clemente",
    "Steve Spodaryk",
    "Tasi O'Malley",
    "Bob Coury",
    "Greg Reid",
    "Kenneth Reeves",
    "Kim Ricket",
    "Susan Gerow",
    "Tom Ricket",
    "Ana Quintana",
    "Gareth Hinds",
    "Jeff Yaus",
    "Kris Size",
    "Michelle Nathan",
    "Christine Reeves",
    "Eileen Christiansen",
    "Erhard Konerding",
    "Lance Nathan",
    "Leah Shuldiner",
    "Mike Scandizzo",
    "Tenille Reichert",
    "Greg Rothauser",
    "Maisie Sturtevant",
    "Sarah San Clemente",
    "Sherry Rinell",
    "Esther Lee",
    "Morgan Harris-Warrick",
    "Aaron Size",
    "Alison Morris",
    "Joyce Farnsworth",
    "Betsy Rosenblatt",
    "Britt Rothauser",
    "Eli Hunt",
    "Jeff Anderson",
    "Katherine Foley",
    "Mike Hsieh",
    "John Nann",
    "Justin Hart",
    "Emily Bernier",
    "Bill Sabram",
    "Marlena Soble",
    "Chris Ercole",
    "Henny Admoni",
    "Jo Agostinelli",
    "Julie Gruszynske",
    "Linda Bennet",
    "Ozzie Osborne",
    "Edgar Fisher",
    "Gretchen Albright",
    "Jen Morris",
    "Tammie Stevens",
    "Ariel Jaffee",
    "Charlotte Wilson",
    "Janet Potter",
    "Lindsay Daviau",
    "Rob Daviau",
    "Bob Marriott",
    "Diana Galanakis",
    "Rich Pellosie",
    "Chelsea Hadlock",
    "Dave Kamin",
    "Deo Gallotto",
    "Erin Rohan",
    "Jill Bourgeois",
    "Marsha Gershon",
    "Nils Klinkenberg",
    "Ben Warren",
    "James Surano",
    "Kayla Schlenz",
    "Jordan Barton",
    "Alex Sheehan",
    "Dana Sullivan",
    "Dave Nadig",
    "Jessica Bodenlos",
    "Julie Leviter",
    "Katie Paugh",
    "Lori Nadig",
    "Matt Miles",
    "Mirin Scassellati",
    "Zak Terry",
    "Laura Hiatt",
    "Mara Feingold-Link",
    "Neal Desai",
    "Scott Moore",
    "Margot Holmes",
    "Mike Robb",
    "Rowan Scassellati",
    "Tricia Boynton",
    "Vanessa Robb",
    "Bri Taborn",
    "Brian Neff",
    "Lane Daniels",
    "Melissa Osborne",
    "Nadav Barkaee",
    "Anna Kelly",
    "Kelsey Schultz",
    "Matthew Scott",
    "Rhea Feiman",
    "Roman Feiman",
    "Cecilia Lindgren",
    "Eleanor Smith-Dufresne",
    "Katherine Greene",
    "Mike Dion",
    "Carl Harkness",
    "Ember Mullen",
    "Ian Osborne",
    "Ken Marden",
    "Madeline Gorey",
    "Ra-Mel McNeil",
    "Tim Ballew"
  ];
}

function getMedicalStaffData() {
  return [
    "Sherry Rinell",
    "Charlotte Wilson",
    "Julie Leviter",
    "Dana Sullivan"
  ];
}
